### ISSUE TITLE
FQDN and Machine Name seem to be swapped when formatting the System report.

### ISSUE THREAD

**Issue by dieterv** [NimaAra/Easy.Common#11]
https://github.com/NimaAra/Easy.Common/blob/a685ce179531adcf386859355dbb694bb471f1eb/Easy.Common/DiagnosticReport/DiagnosticReport.cs#L396

**Comment by NimaAra** [comment]
Thanks for the find, this has now been pushed to _NuGet_ as [v2.8.3](https://www.nuget.org/packages/Easy.Common/2.8.3)
