### ISSUE TITLE
RestClient's AddConnectionLeaseTimeout method - redux

### ISSUE THREAD

**Issue by Andrew-Webb** [NimaAra/Easy.Common#20]
Finding a service endpoint and then setting its `ConnectionLeaseTimeout` value within the SPM for each and every full URI that `RestClient` talks to is potentially wasteful, since - as you say - "the method only cares about the host, schema and port everything else is ignored".

So say the caller of `RestClient` talks to a single API whose base URI is `https://myapi.com/v1/ `. Say you hit this API a 1000 times. `RestClient` will set `ConnectionLeaseTimeout` a 1000 times, but it only needs to do so once.

**Comment by Andrew-Webb** [comment]
Also my other point is that the method is badly named as setting `ConnectionLeaseTimeout` is not all it does.

Should it even do the two things that it does?  (single responsibility principle, and all that)

The method could be called `AddToEndpointHistoryAndSetConnectionLeaseTimeout`...

Or... these two things could be split out into separate methods.

But this is a minor point compared to my main point, which is described in the comment above.

Sorry if neither of these points was clear in my original issue.

**Comment by Andrew-Webb** [comment]
This is a re-open of https://github.com/NimaAra/Easy.Common/issues/18

**Comment by NimaAra** [comment]
Closing this as duplicate. Re-opening #18.
