### ISSUE TITLE
LineCounter doesn't work correctly for eveonline log files

### ISSUE THREAD

**Issue by foxjazz** [NimaAra/Easy.Common#23]
I looked into trying to use this for eveonline log files, and the filecount was incorrect with compared to looping through readline on a StreamReader:

You can reference this project and the monitor.cs file
https://github.com/evetoolsblue/EveIntelReader

Using dotnet core 3.0

**Comment by NimaAra** [comment]
Please provide a sample log reproducing the bug. Thanks.

**Comment by foxjazz** [comment]
https://github.com/foxjazz/EasyNotWorking

**Comment by NimaAra** [comment]
Thank you for the repro.

The provided `Intel.txt` uses a mixture of `LF` and `CRLF` which in my opinion is pure wrong and should not be supported.

IMO, a file must have a single line separator and use that consistently for the rest of the file.

The provided file starts with `CRLF` then changes to `LF` (to print the header) and then switches back to `CRLF` for the rest of the file.

You have the option to ignore the header section and count the actual log files as before.

**Comment by foxjazz** [comment]
I think you need to write it so it's CRLF or CR or LF  This would work better. I didn't look too deep into it, just needed something to work.

**Comment by NimaAra** [comment]
The code as is, supports all three line endings as long as they are consistent throughout the file. As mentioned before, I am not going to support different line endings in a file, if that is what you need then you can do any of the following:

* Ignore the header in your file
* Use ReadLine
* Modify the code to fit your need
