### ISSUE TITLE
IDGenerator for long values

### ISSUE THREAD

**Issue by ifle** [NimaAra/Easy.Common#25]
IDGenerator geenerate the string ID's. Is there a way to generate the long values?

**Comment by NimaAra** [comment]
You can simply base it on: `DateTime.UtcNow.Ticks` and keep incrementing it.

**Comment by ifle** [comment]
It's not safe to run on cluster nodes

**Comment by NimaAra** [comment]
Which is why you need a string id :-)

**Comment by ifle** [comment]
Based on your and CorrelationIdGenerator of asp.net core  implementation I've created my version of IdGenerator
https://gist.github.com/ifle/9328949346d1a616d115f3642ec08e79
