### ISSUE TITLE
.NET Core returns "<INVALID>" Processor Name

### ISSUE THREAD

**Issue by rmillikin** [NimaAra/Easy.Common#27]
Thanks for the great tool! It's been a great help for getting system info for cross-platform .NET programs we're writing.

I've noticed what I think is a bug in getting the processor name in Windows in .NET Core applications. 

https://github.com/NimaAra/Easy.Common/blob/c33434d16eee0a602816a63945192280a37d82dc/Easy.Common/DiagnosticReport/DiagnosticReport.cs#L769

This code block checks for .NET framework or .NET standard targets and returns <INVALID> if the application is not targeted to one of those two. Unfortunately this means that .NET Core applications return "< INVALID >", even though lines 772-773 would work perfectly fine. Can you either remove the targeting requirement, or include .NET Core in the conditional? Or wrap in a try/catch block?

Another request - can you make methods like `GetProcessorName()` and `GetInstalledMemoryInGigaBytes()` `public`? It would be nice to be able to display these outside of your diagnostic report.

I'd be happy to make a pull request - let me know if I should.

**Comment by NimaAra** [comment]
Thanks for reporting.

This should be fixed as of [v3.6.0](https://www.nuget.org/packages/Easy.Common/3.6.0)

With regards to making `GetProcessorName()` and `GetInstalledMemoryInGigaBytes()` public, I prefer them to stay private and internal to the report. 

You have the option of generating specific _SystemDetails_ report by passing the appropriate flag (`DiagnosticReportType.System`) to the `Generate` method. Alternatively you can take those methods and put them into a helper class suitable for your use-case.
