### ISSUE TITLE
CountLines does not reliably support encodings other than UTF-8 / ASCII

### ISSUE THREAD

**Issue by bzaar** [NimaAra/Easy.Common#28]
Here is an example using UTF-16:

    [Test]
    public void CountLinesTest()
    {
        byte[] bytes = Encoding.BigEndianUnicode.GetBytes(" ਊ ");
        var stream = new MemoryStream(bytes);
        Assert.AreEqual(1, Easy.Common.Extensions.StreamExtensions.CountLines(stream));
    }

Results in:

    Expected: 1
    But was:  3

The character I used is U+0a0a which is interpreted as two line feeds by CountLines. Basically any character in the form U+xx0A or U+xx0D or U+0Axx or U+0Dxx can be misinterpreted as an extra line.

I would suggest renaming the method to CountLinesUtf8 or similar.

Or pass in an Encoding / TextReader but then it won't be as fast.

**Comment by NimaAra** [comment]
Thank you for reporting.

Passing a `TextReader` would not address this particular example as the input is too short and the reader cannot correctly identify the encoding.

I prefer the user supplying the encoding with default being _UTF-8_.

This should now be fixed as of [3.7.0](https://www.nuget.org/packages/Easy.Common/3.7.0)
