### ISSUE TITLE
Did not consider the ServicePoint be removed from the servicepointmanager and it's resource get released after a timeout period

### ISSUE THREAD

**Issue by wenzai007** [NimaAra/Easy.Common#29]
https://github.com/NimaAra/Easy.Common/blob/master/Easy.Common/RestClient.cs

You used Hashset in AddConnectionLeaseTimeout  to check whether the service pointhas been set to the ConnectionLeaseTimeout to 1  min. 

But as this https://stackoverflow.com/questions/53653640/net-servicepoint-object-lifecycle says, servicePoint object will be removed from the servicepointmanager and it's resource will get released after a timeout period, so seems your implementation did not consider this. 

Actually, I am wondering have you ever met the issue with the link above said, since from the code I think you will just meet same issue.

**Comment by NimaAra** [comment]
Two things to consider here:

1. `AddConnectionLeaseTimeout` is invoked before every request so even if it is removed it will be added again.

2. None of this is relevant in _.NET Core_ anymore.

**Comment by wenzai007** [comment]
> AddConnectionLeaseTimeout is invoked before every request so even if it is removed it will be added again.

I think you did not get my question at all..  
You used hashset and the key is defined by yourself, so even if the servicepoint object removed underneath, you don't know it since you find the key you created yourself exists, you will ignore and skipping finding the servicepoint and skipping setting the ConnectionLeasetimeout,  so this statement is not correct..


> None of this is relevant in .NET Core anymore.
Your code have if/else, which include net framework version, even net core have no problem with this, why you don't care net framework??
