### ISSUE TITLE
How do you test this RestClient ConnectionLeaseTimeout behavior?

### ISSUE THREAD

**Issue by ChunyuanGe** [NimaAra/Easy.Common#3]
Hi,

Sorry to use this Issues channel as I didn't see any other ways to communicate. I am not using this library directly but I need to set this ServicePointManager.ConnectionLeaseTimeout property. However in my test environment it doesn't work as expected. Do you have any experience on this one? like how to verify behavior?

Thanks
Chunyuan

**Comment by NimaAra** [comment]
Hi,

Take a look at [THIS](http://naeem.khedarun.co.uk/blog/2016/11/30/httpclient-dns-settings-for-azure-cloud-services-and-traffic-manager-1480285049222).

Alternatively you can do an integration/end-2-end test by setting up a test environment on Azure.

Hope this helps.

**Comment by ChunyuanGe** [comment]
Based on what you observed, so even though there're active transaction though this singleton http client, the physically connection will always be reset in every 1 minute? Based on MSDN, client will add NO keep-alive in http header, is that true? or it's a TCP level close action? I was testing locally against another service hosted in Azure however I didn't see the connection(TCP) get reset even though the DnsRefreshTimeout and ConnectionLeaseTimeout are set to 5 seconds. There is another property called MaxIdleTime in ServicePoint works after being inactive for 100 seconds (default) . So I am not sure whether the ConnectionLeaseTimeout is really working.
