### ISSUE TITLE
Decode should use toUpper.

### ISSUE THREAD

**Issue by ppasieka** [NimaAra/Easy.Common#30]
https://github.com/NimaAra/Easy.Common/blob/6fcc1f36d7eaec23a965ab88e8b1eb5b8ee000df/Easy.Common/Base36.cs#L42

With current implementation

Base36.Decode( Base36.Encode(10) ) == 10 // you would expect that but but the result is -1

**Comment by NimaAra** [comment]
Great find, thank you.

Would you be willing to submit a PR?

**Comment by ppasieka** [comment]
Sure, I will do that later today/tomorrow

**Comment by ppasieka** [comment]
nice :) I will close the issue

**Comment by NimaAra** [comment]
This is now available as of [3.8.2](https://www.nuget.org/packages/Easy.Common/3.8.2).
