### ISSUE TITLE
EasyDictionary could just be implemented using KeyedCollection<TKey, TItem>

### ISSUE THREAD

**Issue by kg-github** [NimaAra/Easy.Common#33]
FYI - seems like this is similar to the built in abstract `System.Collections.ObjectModel.KeyedCollection<TKey, TItem>` class.
https://docs.microsoft.com/en-us/dotnet/api/system.collections.objectmodel.keyedcollection-2?view=net-5.0

**Comment by NimaAra** [comment]
It could and indeed that was what I used as the first implementation however `KeyedCollection` has different semantics compared to a `Dictionary` hence I chose the latter as the underlying implementation of `EasyDictionary`.

> The KeyedCollection<TKey,TItem> class is a hybrid between a collection based on the IList<T> generic interface and a collection based on the IDictionary<TKey,TValue> generic interface.
