### ISSUE TITLE
Possible UnauthorizedAccessException in Easy.Common.DiagnosticReport.GetDriveDetails

### ISSUE THREAD

**Issue by RSchwoerer** [NimaAra/Easy.Common#35]
There is a possible exception in Easy.Common.DiagnosticReport.GetDriveDetails when enumerating the details about the connected drives if there is a mapped drive the application or current user does not have access to.
It looks like accessing either VolumeLabel and DriveFormat could throw.

Specifically here: https://github.com/NimaAra/Easy.Common/blob/master/Easy.Common/DiagnosticReport/DiagnosticReport.cs#L298

Easy workaround: 
Exclude drives from the report.
`DiagnosticReport report = DiagnosticReport.Generate(DiagnosticReportType.Full & ~DiagnosticReportType.Drives); `

Proper fix:
Maybe the best way would be to catch the exception and substitute with '-'.

**Comment by NimaAra** [comment]
Thank you for reporting this. Are you able to re-produce and test if I put a fix in a branch?
