### ISSUE TITLE
How to set headers per call

### ISSUE THREAD

**Issue by JesusVFR** [NimaAra/Easy.Common#39]
Hi all,

will be provided a method to set headers per call, in order to keep a single RestClient instance, but passing for instance different JWT Token per call (https://stackoverflow.com/questions/29801195/adding-headers-when-using-httpclient-getasync) ? 

Kindly 
Alessandro

**Comment by NimaAra** [comment]
This is not a question for this repo. Please consider raising this with Microsoft or Stackoverflow.
