### ISSUE TITLE
Adding NotNullWhenAttribute 

### ISSUE THREAD

**Issue by chaddoncooper** [NimaAra/Easy.Common#40]
Are there any blockers to adding NotNullWhenAttribute to methods which contain null checks to remove unnecessary warnings from the compiler?

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings?f1url=%3FappId%3Droslyn%26k%3Dk(CS8618)#possible-dereference-of-null

e.g.
public static bool IsNullOrEmptyOrWhiteSpace([NotNullWhen(false)] this string value) => string.IsNullOrWhiteSpace(value);

Thanks!

**Comment by NimaAra** [comment]
Thank you for reporting this. I will update this hopefully this week.

**Comment by NimaAra** [comment]
[v6.1.0](https://www.nuget.org/packages/Easy.Common/6.1.0) is now available. Can you give it a try?
