### ISSUE TITLE
Is it a better way?

### ISSUE THREAD

**Issue by joshidp** [NimaAra/Easy.Common#7]
Hi

Thanks for the effort.

I don't want to fiddle with ConnectionLeaseTimeout . So is it a better way to create a cache of httpclients based on base uri's. Each unique base uri will have it's own HttpClient. If we have 5 unique uri's we will have 5 items in the cache. URI is our key.

Do you think this is a better approach?

Thanks again!!!

**Comment by NimaAra** [comment]
Okay, and what problem would that solve?

I am closing this issue but feel free to continue your reply on this thread.
