### ISSUE TITLE
Extending Rest Client to expose more method on HttpClient so interfaces are more similar

### ISSUE THREAD

**Issue by insulind** [NimaAra/Easy.Common#8]
Hello!

I commented on your blog post about this and you suggested I should contribute, so here I am, hello :)

Extending the class is simple enough, however I just wanted to get your thoughts on the IRestClient Interface. There is only one implementation in this library but could people have created their own implementations? Extending the interface could break their code which is not good.

My plan b is implement the 'missing' methods as extension methods of IRestClient - this would then not break any existing implementations of IRestClient.

What are you're thoughts?

**Comment by NimaAra** [comment]
Good point, I doubt anyone would have created an implementation even though it is a perfectly reasonable assumption to make. Despite this, I prefer your enhancements to be added to the interface rather than extension methods.

Thanks.

**Comment by insulind** [comment]
Sounds good to me! I'll get a pull request in asap

**Comment by insulind** [comment]
I'm trying to get the Unit tests running and I am having some issues. Is this anything you've experienced? Is there something particular I need to do?

**Comment by NimaAra** [comment]
What is the issue?

**Comment by insulind** [comment]
Its swapping between either not discovering the tests or the while trying to discover the tests the output window says there is an invalid operation exception

**Comment by NimaAra** [comment]
I use the _Resharper_ test runner and/or _NCrunch_ to run the tests. I know that the project does not work with the _Visual Studio_ test runner.

Alternatively you can point the _NUnit Console_ app to the test assembly and make sure the tests are passed.

**Comment by insulind** [comment]
Cool I've used NCrunch and got them running. Without any of my changes I've got 7 tests failed:

- ActiveDirectoryHelperTests

     - When_getting_groups_for_the_current_user:
`An exception was thrown in the Task Environment: System.Net.HttpListenerException (0x80004005): Access is denied
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Easy.Common.Tests.Unit.RestClient.SimpleHttpListener.<ListenAsyncImpl>d__6.MoveNext()`


- RestClientTests 
    - When_sending_a_delete_request
    -When_sending_a_get_request
    -When_sending_a_post_request
    -When_sending_a_request_then_cancelling_all_pending_requests
    -When_sending_a_request_with_cancellation
    -When_sending_a_request_with_cancellation_and_completion_option
    -All with the same exception
    `An exception was thrown in the Task Environment: System.Net.HttpListenerException (0x80004005): Access is denied
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Easy.Common.Tests.Unit.RestClient.SimpleHttpListener.<ListenAsyncImpl>d__6.MoveNext()`

I'm guessing its something to do with my config. Unless you know a quick way of fixing this. I'll add my tests in to PR but I most probably won't be able to run them. Could you confirm they pass once a push them?

**Comment by NimaAra** [comment]
Yes `HttpListener` uses _HTTP.sys_ which requires you to either pre-register the _URL_ prefixes as explained [HERE](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/httpsys#preregister-url-prefixes-and-configure-ssl) or run _VS_ as _Admin_.

If you haven't modified the `ActiveDirectoryHelperTests` then submit the _PR_.

Looking forward to it! :-)

**Comment by NimaAra** [comment]
Excellent! Once again thank you for the _PR_, I will do a release with your changes in the next couple of days.

**Comment by insulind** [comment]
No worries. I Enjoyed it. Hopefully I can contribute more in the future. Thanks for letting me help out!
